package com.angel.e46scannerbt;

import android.app.*;import android.os.*;import android.bluetooth.*;import android.content.*;import android.content.pm.PackageManager;import android.Manifest;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.io.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 LinearLayout root,body,bottom; TextView state,log; BluetoothSocket sock; InputStream in; OutputStream out; BluetoothDevice dev; StringBuilder session=new StringBuilder();
 String volts="--",proto="--",dtc="--",test="LISTO"; int rpm=-1,temp=-999,map=-1,spd=-1,iat=-999; double maf=-1; boolean bt=false,elm=false,prot=false,eng=false,dtcOk=false,backup=false;
 static final UUID SPP=UUID.fromString("00001101-0000-1000-8000-00805F9B34FB"); final int BG=Color.rgb(1,5,11),CARD=Color.rgb(10,17,27),LINE=Color.rgb(25,42,63),TXT=Color.WHITE,MUT=Color.rgb(164,171,183),BLUE=Color.rgb(0,122,255);
 public void onCreate(Bundle b){super.onCreate(b);session.append("BMW E46 SCANNER SESSION\n").append(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).format(new Date())).append("\nCar: BMW E46 coupe 320d/320Cd M47N\nMode: READ ONLY\n\n");showCoding();}
 int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int z,int c,int st){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(0,dp(4),0,dp(4));if(st>0)v.setTypeface(Typeface.DEFAULT,st);return v;} GradientDrawable bg(int c,int r,int line){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(1,line);return g;}
 void shell(String title,boolean fixed){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(22),dp(34),dp(22),dp(6));ScrollView sv=new ScrollView(this);sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);header(title);if(fixed)bottomButtons();}
 void header(String title){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=tv("‹",34,TXT,Typeface.BOLD);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->showHome());h.addView(back,new LinearLayout.LayoutParams(dp(42),dp(44)));TextView t=tv(title,20,TXT,Typeface.BOLD);t.setGravity(Gravity.CENTER);h.addView(t,new LinearLayout.LayoutParams(0,dp(44),1));TextView car=tv("▱",28,TXT,0);car.setGravity(Gravity.CENTER);h.addView(car,new LinearLayout.LayoutParams(dp(42),dp(44)));body.addView(h);state=tv(test+" · BT "+(bt?"OK":"OFF")+" · ELM "+(elm?"OK":"--")+" · "+proto+" · "+volts,12,Color.rgb(120,196,255),0);state.setGravity(Gravity.CENTER);body.addView(state);}
 void tabs(){LinearLayout r=new LinearLayout(this);String[] a={"LUCES","VENTANILLAS","CONFORT","OTROS"};for(String s:a){TextView v=tv(s,12,s.equals("VENTANILLAS")?BLUE:Color.rgb(210,216,225),Typeface.BOLD);v.setGravity(Gravity.CENTER);r.addView(v,new LinearLayout.LayoutParams(0,dp(44),1));}body.addView(r);View line=new View(this);line.setBackgroundColor(BLUE);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(115),dp(2));lp.leftMargin=dp(125);body.addView(line,lp);}
 TextView card(String s,int size){TextView v=tv(s,size,TXT,0);v.setPadding(dp(16),dp(12),dp(16),dp(12));v.setBackground(bg(CARD,10,LINE));return v;} TextView sec(String s){TextView v=tv("\n"+s,12,MUT,0);v.setPadding(0,dp(12),0,dp(7));return v;}
 void showCoding(){shell("Coding Lab",true);tabs();body.addView(card("ⓘ    Personaliza el comportamiento de las ventanillas y funciones de confort asociadas.",14));body.addView(sec("CIERRE CON MANDO"));body.addView(row("Cerrar ventanillas con mantener pulsado","Cierra todas las ventanillas al mantener pulsado el botón de cerrar.",true));body.addView(row("Cerrar ventanillas traseras con mantener","Cierra solo las ventanillas traseras al mantener pulsado el botón de cerrar.",true));body.addView(row("Doble clic para cerrar traseras","Doble clic en el botón de cerrar para subir traseras automáticamente.",true));body.addView(row("Doble clic para abrir traseras","Doble clic en el botón de abrir para bajar traseras automáticamente.",false));body.addView(sec("APERTURA CON MANDO"));body.addView(row("Abrir ventanillas con mantener pulsado","Abre todas las ventanillas al mantener pulsado el botón de abrir.",true));body.addView(row("Doble clic para abrir traseras","Doble clic en el botón de abrir para bajar traseras automáticamente.",true));body.addView(sec("OTRAS OPCIONES"));body.addView(row("Bajar ventanillas al abrir la puerta","Baja ligeramente las ventanillas al abrir la puerta del conductor.",false));body.addView(sec("TESTS / BACKUP"));body.addView(action("Backup seguro READ ONLY",()->safeBackup()));body.addView(action("Test completo automático",()->fullTest()));body.addView(action("Compartir sesión",()->share()));}
 TextView row(String a,String b,boolean on){String sw=on?"        ●":"        ○";TextView v=card(a+sw+"\n"+b,14);v.setTextColor(on?TXT:Color.rgb(195,202,212));return v;}
 TextView action(String s,final Runnable r){TextView v=card(s,15);v.setGravity(Gravity.CENTER);v.setOnClickListener(x->new Thread(r).start());return v;}
 void bottomButtons(){bottom=new LinearLayout(this);bottom.setPadding(dp(22),dp(10),dp(22),dp(16));bottom.setBackgroundColor(Color.rgb(3,7,13));TextView reset=bottomBtn("↻  RESTABLECER",false);reset.setOnClickListener(v->add("RESTABLECER: interfaz, sin escribir."));TextView save=bottomBtn("▣  GUARDAR CAMBIOS",true);save.setOnClickListener(v->add("GUARDAR BLOQUEADO: falta backup real de módulo."));bottom.addView(reset,new LinearLayout.LayoutParams(0,dp(54),1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(54),1);lp.leftMargin=dp(12);bottom.addView(save,lp);root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(80)));}
 TextView bottomBtn(String s,boolean p){TextView v=tv(s,14,p?TXT:BLUE,Typeface.BOLD);v.setGravity(Gravity.CENTER);v.setBackground(p?bg(BLUE,8,BLUE):bg(Color.TRANSPARENT,8,BLUE));return v;}
 void showHome(){shell("Coding Lab E46",false);body.addView(card("Bluetooth  "+(bt?"Conectado":"Desconectado")+"\nBMW E46 320d M47N\nVIN: pendiente\n\n"+live(),15));body.addView(sec("MENÚ PRINCIPAL"));body.addView(menu("Coding Lab","Funciones de confort y personalización",()->showCoding()));body.addView(menu("Backup seguro","Guardar estado OBD/ECU antes de pruebas",()->safeBackup()));body.addView(menu("Diagnóstico","Leer errores y estado de módulos",()->showDiag()));body.addView(menu("Logs","Registros y sesiones guardadas",()->showLogs()));}
 TextView menu(String a,String b,final Runnable r){TextView v=card(a+"                                      ›\n"+b,16);v.setOnClickListener(x->r.run());return v;}
 void showDiag(){shell("Diagnóstico",false);body.addView(card(live(),14));body.addView(card(tests(),13));body.addView(action("Conectar ELM327",()->connect()));body.addView(action("Inicializar ELM",()->initElm()));body.addView(action("Leer motor",()->readEngine()));body.addView(action("Leer DTC",()->runCmds(new String[]{"03","07"},"DTC")));body.addView(action("Compartir sesión",()->share()));addLog();}
 void showLogs(){shell("Logs",false);body.addView(action("Compartir sesión completa",()->share()));body.addView(action("Añadir informe mecánico",()->add(report())));addLog();add("LOG READY. Usa Compartir sesión completa.");}
 void addLog(){log=tv("",12,Color.rgb(220,228,240),0);log.setPadding(dp(14),dp(14),dp(14),dp(14));ScrollView sv=new ScrollView(this);sv.setBackground(bg(Color.rgb(7,12,20),12,Color.rgb(18,30,45)));sv.addView(log);body.addView(sv,new LinearLayout.LayoutParams(-1,dp(240)));}
 String live(){return "RPM  "+val(rpm,"rpm")+"      TEMP  "+val(temp,"°C")+"\nMAP  "+val(map,"kPa")+"      MAF  "+(maf<0?"--":String.format(Locale.US,"%.2f g/s",maf))+"\nVEL  "+val(spd,"km/h")+"      IAT  "+val(iat,"°C")+"\nDTC  "+dtc;} String val(int v,String u){return v<-100||v<0?"--":v+" "+u;} String tests(){return (bt?"●":"○")+" Bluetooth    "+(elm?"●":"○")+" ELM    "+(prot?"●":"○")+" Protocolo\n"+(eng?"●":"○")+" Motor/PIDs    "+(dtcOk?"●":"○")+" DTC    "+(backup?"●":"○")+" Backup";} void refresh(){if(state!=null)runOnUiThread(()->state.setText(test+" · BT "+(bt?"OK":"OFF")+" · ELM "+(elm?"OK":"--")+" · "+proto+" · "+volts));}
 void add(String s){session.append(s).append("\n\n");runOnUiThread(()->{if(log!=null)log.append(s+"\n\n");});} String report(){return "INFORME MECÁNICO\nVoltaje: "+volts+"\nProtocolo: "+proto+"\n"+live()+"\nConclusión: "+(dtc.contains("P0401")?"EGR anulada/desconectada o flujo insuficiente detectado.":"Sin DTC motor confirmado.");}
 void fullTest(){connect();initElm();readEngine();runCmds(new String[]{"03","07"},"DTC");runCmds(new String[]{"ATDP","ATDPN","0100"},"PROTOCOLO");add(report());} void safeBackup(){connect();initElm();add("===== BACKUP SEGURO READ ONLY =====");runCmds(new String[]{"ATI","ATRV","ATDP","ATDPN","0100","0120","0140","0900","0902","0904","03","07","0A"},"BACKUP SEGURO");backup=true;add("BACKUP OK: sesión RAW lista para exportar. No se ha escrito nada.");add(report());refresh();} void share(){try{Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_SUBJECT,"BMW E46 Scanner Session");i.putExtra(Intent.EXTRA_TEXT,session.toString());startActivity(Intent.createChooser(i,"Enviar sesión"));}catch(Exception e){add("ERROR SHARE: "+e.getMessage());}}
 boolean perm(){if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){runOnUiThread(()->requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT},46));return false;}return true;} void connect(){try{test="Conectando BT";refresh();if(!perm())return;BluetoothAdapter a=BluetoothAdapter.getDefaultAdapter();dev=null;for(BluetoothDevice d:a.getBondedDevices()){String n=d.getName()==null?"":d.getName().toLowerCase();if(dev==null||n.contains("obd")||n.contains("elm"))dev=d;}if(dev==null){add("Empareja ELM");return;}close();sock=dev.createRfcommSocketToServiceRecord(SPP);sock.connect();in=sock.getInputStream();out=sock.getOutputStream();bt=true;test="BT OK";add("BT OK: "+dev.getName()+" / "+dev.getAddress());refresh();}catch(Exception e){bt=false;add("ERROR CONEXION: "+e.getClass().getSimpleName()+" - "+e.getMessage());close();refresh();}}
 void close(){try{if(sock!=null)sock.close();}catch(Exception e){}sock=null;in=null;out=null;} boolean ready(){if(sock==null||!sock.isConnected()||in==null||out==null){add("Pulsa conectar primero");return false;}return true;} void initElm(){runCmds(new String[]{"ATZ","ATE0","ATL0","ATS0","ATH1","ATI","ATRV","ATSP0","ATDP","ATDPN"},"INIT ELM");elm=true;} void readEngine(){runCmds(new String[]{"0120","010C","010C","0105","010D","010B","010F","0110"},"MOTOR");eng=true;}
 void runCmds(String[] cs,String name){try{if(!ready())return;test=name;add("===== "+name+" =====");for(String c:cs)send(c);if(name.contains("DTC"))dtcOk=true;if(name.contains("PROTOCOLO"))prot=true;test=name+" terminado";refresh();}catch(Exception e){add("ERROR "+name+": "+e.getClass().getSimpleName()+" - "+e.getMessage());close();refresh();}} void send(String c)throws Exception{out.write((c+"\r").getBytes("US-ASCII"));out.flush();Thread.sleep(c.equals("ATZ")?1700:1000);String r=read();add("> "+c+"\n"+r);parse(c,r);refresh();} String read()throws Exception{byte[] b=new byte[512];StringBuilder s=new StringBuilder();long end=System.currentTimeMillis()+1600;while(System.currentTimeMillis()<end){while(in.available()>0){int n=in.read(b);if(n>0)s.append(new String(b,0,n,"US-ASCII"));}if(s.toString().contains(">"))break;Thread.sleep(60);}String r=s.toString().replace('\r',' ').replace('\n',' ').trim();return r.length()==0?"SIN RESPUESTA":r;}
 void parse(String cmd,String r){try{if(cmd.equals("ATRV"))volts=r.replace(">","").trim();if(cmd.equals("ATDP"))proto=r.replace(">","").trim();String h=r.replace(" ","").replace(">","");int i;if((i=h.indexOf("410C"))>=0){int a=Integer.parseInt(h.substring(i+4,i+6),16),b=Integer.parseInt(h.substring(i+6,i+8),16);rpm=((a*256)+b)/4;}if((i=h.indexOf("4105"))>=0)temp=Integer.parseInt(h.substring(i+4,i+6),16)-40;if((i=h.indexOf("410D"))>=0)spd=Integer.parseInt(h.substring(i+4,i+6),16);if((i=h.indexOf("410B"))>=0)map=Integer.parseInt(h.substring(i+4,i+6),16);if((i=h.indexOf("410F"))>=0)iat=Integer.parseInt(h.substring(i+4,i+6),16)-40;if((i=h.indexOf("4110"))>=0){int a=Integer.parseInt(h.substring(i+4,i+6),16),b=Integer.parseInt(h.substring(i+6,i+8),16);maf=((a*256)+b)/100.0;}if(h.contains("430401"))dtc="P0401 EGR insuficiente";else if(h.contains("43"))dtc="DTC RAW";}catch(Exception e){}}
}
